from enum import Enum
from pydantic import BaseModel


class Analysis(str, Enum):
    """
    Supported analyses to run on datasets
    """

    tcl = "tcl"
    glad = "glad"
    viirs = "viirs"
    modis = "modis"


class AnalysisInputTable(BaseModel):
    """
    A table generated by running an analysis on an existing dataset/version.
    """

    dataset: str
    version: str
    analysis: Analysis
