import os
import logging

LOGGER = logging.getLogger("datapump")

DATA_API_URI = os.environ.get("DATA_API_URI", None)
DYNAMODB_DB_TABLE = ""

AWS_REGION = ""
RESULT_BUCKET = ""
MASTER_INSTANCE_TYPE = ""
WORKER_INSTANCE_TYPES = ""
EC2_KEY_NAME = ""
PUBLIC_SUBNET_IDS = ""
EMR_INSTANCE_PROFILE = os.environ.get("EMR_INSTANCE_PROFILE", None)
EMR_SERVICE_ROLE = os.environ.get("EMR_SERVICE_ROLE", None)

EMR_VERSION = "emr-5.24.0"

GEOTRELLIS_JAR_PATH = ""
WORKER_COUNT_MIN = 5
WORKER_COUNT_PER_GB_FEATURES = 50
