from enum import Enum
from typing import List

from pydantic import BaseModel


class JobStatus(str, Enum):
    starting = "starting"
    analyzing = "analyzing"
    analyzed = "analyzed"
    uploading = "uploading"
    complete = "complete"
    failed = "failed"


class Job(BaseModel):
    id: str
    status: JobStatus = JobStatus.starting


class Analysis(str, Enum):
    """
    Supported analyses to run on datasets
    """

    tcl = "tcl"
    glad = "glad"
    viirs = "viirs"
    modis = "modis"


class AnalysisInputTable(BaseModel):
    """
    A table generated by running an analysis on an existing dataset/version.
    """

    dataset: str
    version: str
    analysis: Analysis


class AnalysisTable(BaseModel):
    """
    A table generated by running an analysis on an existing dataset/version.
    """

    dataset: str
    analysis: Analysis
    analysis_version: str


class PartitionSchema(BaseModel):
    partition_type: str
    partition_column: str
    partition_values: List[str]


class AnalysisResultTable(BaseModel):
    dataset: str
    version: str
    source_uri: List[str]
    index_columns: List[str] = None
    partitions: PartitionSchema = None
