#!/usr/bin/env bash

set -e

export ENV=test
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test

#docker network create test || true
docker-compose -f tests/docker-compose-localstack.yml up --remove-orphans -d
sleep 10s

## copy lambda layer zips to test folder, so we can upload them to localstack
#aws s3 cp s3://gfw-pipelines-dev/lambda_layers/shapely_pyyaml.zip tests/files/shapely_pyyaml.zip --profile gfw-dev
#aws s3 cp s3://gfw-pipelines-dev/lambda_layers/rasterio.zip tests/files/rasterio.zip --profile gfw-dev

## just use default roles for EMR, need to be created with this call first
## for some awslocal doesn't work, had to manually specify endpoint
aws emr create-default-roles --iam-endpoint http://localhost:4566

pushd tests/terraform
(terraform init && \
  terraform destroy -var-file="terraform-test.tfvars" -auto-approve && \
  terraform plan -var-file="terraform-test.tfvars" && \
  terraform apply -var-file="terraform-test.tfvars" -auto-approve) || truw
popd

pytest tests/tests || true

docker-compose -f tests/docker-compose-localstack.yml stop
docker-compose -f tests/docker-compose-localstack.yml rm -f

rm tests/terraform/terraform.tfstate*