#!/usr/bin/env bash

set -e

export ENV=test
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test

docker network create test || true
docker-compose -f tests/docker-compose-mock.yml up --remove-orphans -d

# need to sleep to make sure localstack has time to start up all services
sleep 20s

pushd tests/files/mock_geotrellis
mvn package
popd

pushd tests/terraform
(terraform init && terraform destroy -var-file="terraform-test.tfvars" -auto-approve && terraform plan -var-file="terraform-test.tfvars" && terraform apply -var-file="terraform-test.tfvars" -auto-approve) || true
popd

pytest tests/tests || true

docker-compose -f tests/docker-compose-mock.yml logs -t localstack > tests/logs/localstack.log
docker-compose -f tests/docker-compose-mock.yml logs -t mock_server > tests/logs/mock_server.log

docker-compose -f tests/docker-compose-mock.yml stop
docker-compose -f tests/docker-compose-mock.yml rm -f

# delete if exists, otherwise localstack might have issues with EMR on next run
docker rm -f localstack_bigdata || true

rm tests/terraform/terraform.tfstate*