python ./tools/create_datasets.py --features s3://gfw-files/2018_update/tsv/gadm36_adm2_1_1.csv --feature_type gadm --worker_count 150 --analysis annualupdate_minimal --version v20201027 --tcl_year 2019 --env production
python ./tools/create_datasets.py --features s3://gfw-files/2018_update/tsv/gadm36_adm2_1_1.csv --feature_type gadm --worker_count 100 --analysis firealerts --version v20201027 --fire_alert_type viirs --env production
python ./tools/create_datasets.py --features s3://gfw-files/2018_update/tsv/gadm36_adm2_1_1.csv --feature_type gadm --worker_count 100 --analysis firealerts --version v20201027 --fire_alert_type modis --env production
python ./tools/create_datasets.py --features s3://gfw-files/2018_update/tsv/gadm36_adm2_1_1.csv --feature_type gadm --worker_count 100 --analysis gladalerts --version v20201027 --env production
python ./tools/create_datasets.py --features "s3://gfw-pipelines/geotrellis/features/geostore/*.tsv" --feature_type geostore --worker_count 150 --analysis annualupdate_minimal --version v20201027 --tcl_year 2019 --env production
python ./tools/create_datasets.py --features "s3://gfw-pipelines/geotrellis/features/geostore/*.tsv" --feature_type geostore --worker_count 100 --analysis gladalerts --version v20201027 --env production
python ./tools/create_datasets.py --features "s3://gfw-pipelines/geotrellis/features/geostore/*.tsv" --feature_type geostore --worker_count 100 --analysis firealerts --version v20201027 --env production --fire_alert_type viirs
python ./tools/create_datasets.py --features "s3://gfw-pipelines/geotrellis/features/geostore/*.tsv" --feature_type geostore --worker_count 100 --analysis firealerts --version v20201027 --env production --fire_alert_type modis

python ./tools/create_datasets.py --features s3://gfw-data-lake/wdpa_protected_areas/v202010/vector/epsg-4326/wdpa_protected_areas_v202010_1x1.tsv  --feature_type wdpa --worker_count 100 --analysis gladalerts --version v20201027 --env production
python ./tools/create_datasets.py --features s3://gfw-data-lake/wdpa_protected_areas/v202010/vector/epsg-4326/wdpa_protected_areas_v202010_1x1.tsv --feature_type wdpa --worker_count 150 --analysis annualupdate_minimal --version v20201027 --tcl_year 2019 --env production
python ./tools/create_datasets.py --features s3://gfw-data-lake/wdpa_protected_areas/v202010/vector/epsg-4326/wdpa_protected_areas_v202010_1x1.tsv --feature_type wdpa --worker_count 80 --analysis firealerts --version v20201027 --fire_alert_type viirs --env production
python ./tools/create_datasets.py --features s3://gfw-data-lake/wdpa_protected_areas/v202010/vector/epsg-4326/wdpa_protected_areas_v202010_1x1.tsv  --feature_type wdpa --worker_count 80 --analysis firealerts --version v20201027 --fire_alert_type modis --env production